name: Deploy to Amazon EC2 

on: 
  push: 
    branches: [ "main" ]

jobs: 
  deploy: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Code 
        uses: actions/checkout@v4

      - name: Deploy via SSH 
        uses: appleboy/ssh-action@v1.0.3
        with: 
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu 
          key: ${{ secrets.EC2_SSH_KEY }}
          script: | 
            cd ~/Quiz_Test || git clone https://github.com/${{ github.repository }}.git ~/Quiz_Test
            cd ~/Quiz_Test
            git pull origin main 
            sudo docker-compose down || sudo docker compose down
            sudo docker-compose up -d --build || sudo docker compose up -d --build